/**
 * Nitro display-name fonts, embedded into the card.
 *
 * Discord styles names with Google Fonts and reports the choice as `font_id`.
 * A webfont cannot be linked from an SVG that GitHub serves through its image
 * proxy, so the file travels inside the document as a data URI — the same
 * reason every image here is inlined. Verified to render in Chromium when the
 * SVG is loaded as `<img>`.
 *
 * The files live in `assets/fonts/` under the SIL Open Font License 1.1; see
 * `assets/fonts/LICENSES.md`. `npm run fonts` refreshes them.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

interface FontEntry {
  family: string;
  file: string;
  weight: number;
}

const DIR = new URL("../../assets/fonts/", import.meta.url);

/** Generated by scripts/fetch-fonts.mjs; an unknown id keeps the card font. */
const INDEX: Record<string, FontEntry> = JSON.parse(
  readFileSync(fileURLToPath(new URL("index.json", DIR)), "utf8"),
);

/** Each font is read and encoded once; the process serves the same few forever. */
const encoded = new Map<string, string | null>();

function dataUri(entry: FontEntry): string | null {
  const cached = encoded.get(entry.file);
  if (cached !== undefined) return cached;

  let value: string | null = null;
  try {
    const bytes = readFileSync(fileURLToPath(new URL(entry.file, DIR)));
    value = `data:font/woff2;base64,${bytes.toString("base64")}`;
  } catch (error) {
    console.warn("font missing", { file: entry.file, error: String(error) });
  }
  encoded.set(entry.file, value);
  return value;
}

export interface EmbeddedFont {
  family: string;
  /** A complete @font-face rule, ready to drop into a <style> element. */
  face: string;
}

export function embeddedFont(fontId: number | undefined): EmbeddedFont | null {
  if (fontId === undefined) return null;
  const entry = INDEX[String(fontId)];
  if (!entry) return null;

  const uri = dataUri(entry);
  if (!uri) return null;

  return {
    family: entry.family,
    face:
      `@font-face{font-family:'${entry.family}';` +
      `src:url(${uri}) format('woff2');font-weight:${entry.weight};font-display:block}`,
  };
}
